name: AAAActions Testing with tag mock

on:
  push:
    branches: '*'
  workflow_dispatch:
    inputs:
      key1:
        description: 'key1 input example'
        required: false
    # leave blank to allow manual deploys

permissions:
  contents: read

jobs:
  setup-runner:
    name: test setup runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pretend deploy to CI
        run: echo "Wow, that was a quick deploy to CI!"
