name: name of action
on:
  push:
    branches: '*'

jobs:
  pytest-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init python
        run: |
          python --version
          pip install -r requirements.txt

      - name: Run pytest 
        run: |
          pytest --cov=. --cov-fail-under=90 > coverage_report.txt
          cat .coverage
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-coverage-report
          path: coverage_report.txt
            
