name: name of action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  newname:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Init python
        run: python --version

      # - name: Run pytest
      #   run: pytest --cov

 
